spring.profiles.include=secret
spring.application.name=moodwave




# driver = Mysql 전용 드라이버 클래스 (Mysql 8.x 버전용)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mybatis 설정
# VO 클래스가 있는 패키지 등록 -> 쿼리 결과를 VO 객체로 자동 변환해줌
mybatis.type-aliases-package=com.example.demo.vo
# DB 컬럼명(img_url)을 Java 필드명 (imgUrl)으로 자동 변환 (언더스코어 -> 카멜케이스)
mybatis.configuration.map-underscore-to-camel-case=true