spring.profiles.include=secret
spring.application.name=moodwave

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.type-aliases-package=com.example.demo.vo
mybatis.configuration.map-underscore-to-camel-case=true

spring.security.oauth2.client.registration.spotify.scope=user-read-private,user-read-email,streaming

spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me
spring.security.oauth2.client.provider.spotify.user-name-attribute=id